### ISSUE TITLE
Enable use with short_open_tag = Off

### ISSUE THREAD

**Issue by mathiassiegmund** [christianreber/kirbycms-knowledge-base#1]
Use of knowledge base isn't possible if `short_open_tag` in `php.ini` is set to `Off`, which is the recommended setting for development & production.

Please change usages of `<?` to `<?php`

**Comment by mathiassiegmund** [comment]
Created pull request #2 with solution (https://github.com/christianreber/kirbycms-knowledge-base/pull/2)

**Comment by christianreber** [comment]
Thanks!
