### ISSUE TITLE
License of this theme?

### ISSUE THREAD

**Issue by hoffleit** [christianreber/kirbycms-knowledge-base#3]
Could you please state the license this theme is distributed under?

The only copyright or license terms I could find in the code were the license boilerplates in the GeSHi code, which is licensed under the GPL. This might be a problem with Kirby.

**Comment by christianreber** [comment]
I haven't used any specific license, it's simply open source. Bastian (the creator behind Kirby) has no problem with this theme.

**Comment by hoffleit** [comment]
Christian, sorry to be nitpicky, but
(a) Then I guess you really mean "it's in the public domain". In the end "simply open source" is no useful statement, but only a description of intents.
(b) I meant that the author of GeSHi might have a problem with the distribution of GeSHi with a plugin for Kirby. Arguably, the license terms of GeSHi don't permit this.
