### ISSUE TITLE
PHP Short Tags

### ISSUE THREAD

**Issue by tysongach** [christianreber/kirbycms-knowledge-base#7]
I would recommend adding a note to the README that this theme makes use of PHP short tags and users might need to enable that for it to work.

Since they are sprinkled throughout the themes and not always used, I missed that fact when I first installed it, but then finally realized they were being used.

There’s a blog post on the Kirby site that talks about this and you can link unaware people to that: http://getkirby.com/blog/php-templates

**Comment by ghost** [comment]
Hi Tyson,

Does https://github.com/christianreber/kirbycms-knowledge-base/pull/2 resolve this issue for you?

Thanks

**Comment by tysongach** [comment]
Must have! Just downloaded the latest version and it all works. A couple of months ago, I downloaded this theme and certain pieces weren't working until I realized I needed to toggle on PHP short tags. I actually like using short tags, but was just caught off guard without mention in the readme.

Thanks!
